apiVersion: apps/v1
kind: Deployment
metadata:
  name: asm-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asm-ai
  template:
    metadata:
      labels:
        app: asm-ai
    spec:
      containers:
      - name: asm-ai
        image: knnrsolomon/asm-ai-backend:v7-final-clean
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: asm-ai-secret
              key: OPENAI_API_KEY

        - name: JWT_SECRET
          value: "supersecret"

        # 🔥 STORAGE
        volumeMounts:
        - name: asm-ai-storage
          mountPath: /app/backend/data

      volumes:
      - name: asm-ai-storage
        persistentVolumeClaim:
          claimName: asm-ai-pvc
